# fly.toml app configuration file generated for billowing-glade-1070 on 2023-06-05T13:25:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-glade-1070"
primary_region = "mia"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_TARGETS = "./cmd/server"

[env]
  PORT = "8080"
  SQLITE_VOLUME = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source="sqlite"
  destination="/data"
